chain:
  block_time: 2s
  irreversible_distance: 50
  client:
    http_timeout: 600s
sla:
  block_height_delta: 400
  block_time_delta: 2m
  out_of_sync_node_distance: 400
  tier: 2
  time_since_last_block: 3m
  event_height_delta: 400
  event_time_delta: 2m
  time_since_last_event: 3m
workflows:
  backfiller:
    batch_size: 1500
    checkpoint_size: 3000
    num_concurrent_extractors: 36
    activity_start_to_close_timeout: 20m
  poller:
    backoff_interval: 0s
    fast_sync: false
    parallelism: 30
    max_blocks_to_sync_per_cycle: 300
    session_enabled: true
  streamer:
    backoff_interval: 0s
  monitor:
    backoff_interval: 0s
    parallelism: 10
