// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coinbase/chainstorage/internal/storage/blobstorage/downloader (interfaces: BlockDownloader)
//
// Generated by this command:
//
//	mockgen -destination internal/storage/blobstorage/downloader/mocks/mocks.go -package downloadermocks github.com/coinbase/chainstorage/internal/storage/blobstorage/downloader BlockDownloader
//

// Package downloadermocks is a generated GoMock package.
package downloadermocks

import (
	context "context"
	reflect "reflect"

	downloader "github.com/coinbase/chainstorage/internal/storage/blobstorage/downloader"
	chainstorage "github.com/coinbase/chainstorage/protos/coinbase/chainstorage"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockDownloader is a mock of BlockDownloader interface.
type MockBlockDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockBlockDownloaderMockRecorder
}

// MockBlockDownloaderMockRecorder is the mock recorder for MockBlockDownloader.
type MockBlockDownloaderMockRecorder struct {
	mock *MockBlockDownloader
}

// NewMockBlockDownloader creates a new mock instance.
func NewMockBlockDownloader(ctrl *gomock.Controller) *MockBlockDownloader {
	mock := &MockBlockDownloader{ctrl: ctrl}
	mock.recorder = &MockBlockDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockDownloader) EXPECT() *MockBlockDownloaderMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockBlockDownloader) Download(arg0 context.Context, arg1 *chainstorage.BlockFile) (*chainstorage.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockBlockDownloaderMockRecorder) Download(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockBlockDownloader)(nil).Download), arg0, arg1)
}

// DownloadStream mocks base method.
func (m *MockBlockDownloader) DownloadStream(arg0 context.Context, arg1 *chainstorage.BlockFile) (*chainstorage.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadStream", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadStream indicates an expected call of DownloadStream.
func (mr *MockBlockDownloaderMockRecorder) DownloadStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadStream", reflect.TypeOf((*MockBlockDownloader)(nil).DownloadStream), arg0, arg1)
}

// DownloadStreamBitcoin mocks base method.
func (m *MockBlockDownloader) DownloadStreamBitcoin(arg0 context.Context, arg1 *chainstorage.BlockFile) (*downloader.BitcoinStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadStreamBitcoin", arg0, arg1)
	ret0, _ := ret[0].(*downloader.BitcoinStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadStreamBitcoin indicates an expected call of DownloadStreamBitcoin.
func (mr *MockBlockDownloaderMockRecorder) DownloadStreamBitcoin(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadStreamBitcoin", reflect.TypeOf((*MockBlockDownloader)(nil).DownloadStreamBitcoin), arg0, arg1)
}
