version: "3"

services:
  localstack:
    image: localstack/localstack:3.1.0
    ports:
      - 4566:4566
      - 4510-4559:4510-4559  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=requirednotused
      - AWS_SECRET_ACCESS_KEY=requirednotused
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    command: >
      postgres
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    volumes:
      - ./scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
    restart: always