aws:
  bucket: example-chainstorage-{{blockchain}}-{{network}}-{{short_env}}
  aws_account: production
cadence:
  address: temporal.example.com:7233
sdk:
  chainstorage_address: https://nft-api.coinbase.com/api/exp/chainstorage/{{blockchain}}/{{network}}/v1
