chain:
  block_time: 1s
  event_tag:
    latest: 1
    stable: 1
  irreversible_distance: 1
sla:
  block_height_delta: 100
  block_time_delta: 2m
  out_of_sync_node_distance: 100
  tier: 2
  time_since_last_block: 3m
  event_height_delta: 100
  event_time_delta: 2m
  time_since_last_event: 3m
workflows:
  backfiller:
    num_concurrent_extractors: 25
  monitor:
    backoff_interval: 1s
  poller:
    backoff_interval: 1s
    fast_sync: true
  streamer:
    backoff_interval: 1s
  migrator:
    activity_retry:
      backoff_coefficient: 2
      initial_interval: 10s
      maximum_attempts: 3
      maximum_interval: 3m
    activity_schedule_to_close_timeout: 1h
    activity_start_to_close_timeout: 30m
    backoff_interval: 5s
    batch_size: 1000
    checkpoint_size: 5000
    task_list: default
    workflow_identity: workflow.migrator
    workflow_run_timeout: 24h
