
chain:
  client:
    master:
      endpoint_group:
        endpoints:
          - name: getblock
            url: ""
            weight: 1
            rps: 1
    slave:
      endpoint_group:
        endpoints:
          - name: getblock
            url: ""
            weight: 1
            rps: 1
    validator:
      endpoint_group:
        endpoints:
          - name: getblock
            url: ""
            weight: 1
            rps: 1
workflows:
  poller:
    failover_enabled: false
  monitor:
    failover_enabled: false

