chain:
  event_tag:
    latest: 2
    stable: 0
  feature:
    default_stable_event: false
aws:
  aws_account: development
sla:
  block_height_delta: 12
  block_time_delta: 3m
  out_of_sync_node_distance: 12
  time_since_last_block: 3m
  event_height_delta: 12
  event_time_delta: 3m
  time_since_last_event: 3m
  expected_workflows:
    - monitor
    - poller
    - streamer
    - streamer/event_tag=1
    - streamer/event_tag=2
    - cross_validator
workflows:
  migrator:
    activity_retry:
      backoff_coefficient: 2
      initial_interval: 10s
      maximum_attempts: 3
      maximum_interval: 3m
    activity_schedule_to_close_timeout: 1h
    activity_start_to_close_timeout: 30m
    backoff_interval: 5s
    batch_size: 1000
    checkpoint_size: 5000
    task_list: default
    workflow_identity: workflow.migrator
    workflow_run_timeout: 24h
  poller:
    failover_enabled: false
  monitor:
    failover_enabled: false
