chain:
  block_time: 300ms
  event_tag:
    latest: 1
    stable: 1
  irreversible_distance: 1
sla:
  block_height_delta: 200
  block_time_delta: 1m
  out_of_sync_node_distance: 500
  out_of_sync_validator_node_distance: 1200
  tier: 2
  time_since_last_block: 1m30s
  event_height_delta: 200
  event_time_delta: 1m
  time_since_last_event: 1m30s
  expected_workflows:
    - monitor
    - poller
    - streamer
    - cross_validator
workflows:
  backfiller:
    num_concurrent_extractors: 300
  monitor:
    backoff_interval: 1s
  poller:
    backoff_interval: 0s
    fast_sync: true
    max_blocks_to_sync_per_cycle: 200
    parallelism: 50
  streamer:
    backoff_interval: 0s
  cross_validator:
    batch_size: 1000
    validation_start_height: 22207816 # CREL nodes do not support arb_trace API which was used before the NITRO upgrade
    validation_percentage: 1
    irreversible_distance: 500
