aws:
  aws_account: production
cadence:
  keep_alive_time: 10s
  keep_alive_timeout: 30s
cron:
  batch_consolidator:
    workflow_parallelism: 2
workflows:
  backfiller:
    num_concurrent_extractors: 150
