// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coinbase/chainstorage/internal/storage/blobstorage (interfaces: BlobStorage,SingleBlockUploader)
//
// Generated by this command:
//
//	mockgen -destination internal/storage/blobstorage/mocks/mocks.go -package blobstoragemocks github.com/coinbase/chainstorage/internal/storage/blobstorage BlobStorage,SingleBlockUploader
//

// Package blobstoragemocks is a generated GoMock package.
package blobstoragemocks

import (
	context "context"
	reflect "reflect"

	internal "github.com/coinbase/chainstorage/internal/storage/blobstorage/internal"
	chainstorage "github.com/coinbase/chainstorage/protos/coinbase/chainstorage"
	gomock "go.uber.org/mock/gomock"
)

// MockBlobStorage is a mock of BlobStorage interface.
type MockBlobStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBlobStorageMockRecorder
}

// MockBlobStorageMockRecorder is the mock recorder for MockBlobStorage.
type MockBlobStorageMockRecorder struct {
	mock *MockBlobStorage
}

// NewMockBlobStorage creates a new mock instance.
func NewMockBlobStorage(ctrl *gomock.Controller) *MockBlobStorage {
	mock := &MockBlobStorage{ctrl: ctrl}
	mock.recorder = &MockBlobStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobStorage) EXPECT() *MockBlobStorageMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockBlobStorage) Download(arg0 context.Context, arg1 *chainstorage.BlockMetadata) (*chainstorage.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockBlobStorageMockRecorder) Download(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockBlobStorage)(nil).Download), arg0, arg1)
}

// DownloadMany mocks base method.
func (m *MockBlobStorage) DownloadMany(arg0 context.Context, arg1 []*chainstorage.BlockMetadata) ([]*chainstorage.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadMany", arg0, arg1)
	ret0, _ := ret[0].([]*chainstorage.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadMany indicates an expected call of DownloadMany.
func (mr *MockBlobStorageMockRecorder) DownloadMany(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadMany", reflect.TypeOf((*MockBlobStorage)(nil).DownloadMany), arg0, arg1)
}

// PreSign mocks base method.
func (m *MockBlobStorage) PreSign(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreSign", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreSign indicates an expected call of PreSign.
func (mr *MockBlobStorageMockRecorder) PreSign(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreSign", reflect.TypeOf((*MockBlobStorage)(nil).PreSign), arg0, arg1)
}

// UploadConsolidated mocks base method.
func (m *MockBlobStorage) UploadConsolidated(arg0 context.Context, arg1 []internal.ConsolidatedBlockPayload) (string, []internal.BlockPlacement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadConsolidated", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]internal.BlockPlacement)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UploadConsolidated indicates an expected call of UploadConsolidated.
func (mr *MockBlobStorageMockRecorder) UploadConsolidated(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadConsolidated", reflect.TypeOf((*MockBlobStorage)(nil).UploadConsolidated), arg0, arg1)
}

// MockSingleBlockUploader is a mock of SingleBlockUploader interface.
type MockSingleBlockUploader struct {
	ctrl     *gomock.Controller
	recorder *MockSingleBlockUploaderMockRecorder
}

// MockSingleBlockUploaderMockRecorder is the mock recorder for MockSingleBlockUploader.
type MockSingleBlockUploaderMockRecorder struct {
	mock *MockSingleBlockUploader
}

// NewMockSingleBlockUploader creates a new mock instance.
func NewMockSingleBlockUploader(ctrl *gomock.Controller) *MockSingleBlockUploader {
	mock := &MockSingleBlockUploader{ctrl: ctrl}
	mock.recorder = &MockSingleBlockUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSingleBlockUploader) EXPECT() *MockSingleBlockUploaderMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockSingleBlockUploader) Upload(arg0 context.Context, arg1 *chainstorage.Block, arg2 chainstorage.Compression) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockSingleBlockUploaderMockRecorder) Upload(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockSingleBlockUploader)(nil).Upload), arg0, arg1, arg2)
}

// UploadRaw mocks base method.
func (m *MockSingleBlockUploader) UploadRaw(arg0 context.Context, arg1 *internal.RawBlockData) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadRaw", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadRaw indicates an expected call of UploadRaw.
func (mr *MockSingleBlockUploaderMockRecorder) UploadRaw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadRaw", reflect.TypeOf((*MockSingleBlockUploader)(nil).UploadRaw), arg0, arg1)
}
