chain:
  block_time: 1m
  event_tag:
    latest: 0
    stable: 0
  rosetta:
    blockchain: dogecoin
    network: mainnet
    block_not_found_error_codes: 4
  feature:
    rosetta_parser: true
  irreversible_distance: 60
aws:
  dynamodb:
    event_table: example_chainstorage_block_events_{{blockchain}}_{{network}}
    event_table_height_index: example_chainstorage_block_events_by_height_{{blockchain}}_{{network}}
cron:
  disable_dlq_processor: true
sla:
  block_height_delta: 10
  block_time_delta: 10m
  out_of_sync_node_distance: 10
  tier: 2
  time_since_last_block: 15m
  event_height_delta: 10
  event_time_delta: 10m
  time_since_last_event: 15m
workflows:
  backfiller:
    num_concurrent_extractors: 24
  poller:
    parallelism: 10
    max_blocks_to_sync_per_cycle: 50
    session_enabled: true
