// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/coinbase/chainstorage/internal/storage/metastorage (interfaces: MetaStorage,EventStorage,BlockStorage,TransactionStorage)
//
// Generated by this command:
//
//	mockgen -destination internal/storage/metastorage/mocks/mocks.go -package metastoragemocks github.com/coinbase/chainstorage/internal/storage/metastorage MetaStorage,EventStorage,BlockStorage,TransactionStorage
//

// Package metastoragemocks is a generated GoMock package.
package metastoragemocks

import (
	context "context"
	reflect "reflect"
	time "time"

	internal "github.com/coinbase/chainstorage/internal/storage/metastorage/internal"
	model "github.com/coinbase/chainstorage/internal/storage/metastorage/model"
	chainstorage "github.com/coinbase/chainstorage/protos/coinbase/chainstorage"
	gomock "go.uber.org/mock/gomock"
)

// MockMetaStorage is a mock of MetaStorage interface.
type MockMetaStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetaStorageMockRecorder
}

// MockMetaStorageMockRecorder is the mock recorder for MockMetaStorage.
type MockMetaStorageMockRecorder struct {
	mock *MockMetaStorage
}

// NewMockMetaStorage creates a new mock instance.
func NewMockMetaStorage(ctrl *gomock.Controller) *MockMetaStorage {
	mock := &MockMetaStorage{ctrl: ctrl}
	mock.recorder = &MockMetaStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaStorage) EXPECT() *MockMetaStorageMockRecorder {
	return m.recorder
}

// AddEventEntries mocks base method.
func (m *MockMetaStorage) AddEventEntries(arg0 context.Context, arg1 uint32, arg2 []*model.EventEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventEntries", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEventEntries indicates an expected call of AddEventEntries.
func (mr *MockMetaStorageMockRecorder) AddEventEntries(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventEntries", reflect.TypeOf((*MockMetaStorage)(nil).AddEventEntries), arg0, arg1, arg2)
}

// AddEvents mocks base method.
func (m *MockMetaStorage) AddEvents(arg0 context.Context, arg1 uint32, arg2 []*model.BlockEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEvents indicates an expected call of AddEvents.
func (mr *MockMetaStorageMockRecorder) AddEvents(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvents", reflect.TypeOf((*MockMetaStorage)(nil).AddEvents), arg0, arg1, arg2)
}

// AddTransactions mocks base method.
func (m *MockMetaStorage) AddTransactions(arg0 context.Context, arg1 []*model.Transaction, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTransactions", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTransactions indicates an expected call of AddTransactions.
func (mr *MockMetaStorageMockRecorder) AddTransactions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTransactions", reflect.TypeOf((*MockMetaStorage)(nil).AddTransactions), arg0, arg1, arg2)
}

// GetBlockByHash mocks base method.
func (m *MockMetaStorage) GetBlockByHash(arg0 context.Context, arg1 uint32, arg2 uint64, arg3 string) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHash", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHash indicates an expected call of GetBlockByHash.
func (mr *MockMetaStorageMockRecorder) GetBlockByHash(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHash", reflect.TypeOf((*MockMetaStorage)(nil).GetBlockByHash), arg0, arg1, arg2, arg3)
}

// GetBlockByHeight mocks base method.
func (m *MockMetaStorage) GetBlockByHeight(arg0 context.Context, arg1 uint32, arg2 uint64) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHeight", arg0, arg1, arg2)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHeight indicates an expected call of GetBlockByHeight.
func (mr *MockMetaStorageMockRecorder) GetBlockByHeight(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHeight", reflect.TypeOf((*MockMetaStorage)(nil).GetBlockByHeight), arg0, arg1, arg2)
}

// GetBlockByTimestamp mocks base method.
func (m *MockMetaStorage) GetBlockByTimestamp(arg0 context.Context, arg1 uint32, arg2 uint64) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByTimestamp", arg0, arg1, arg2)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByTimestamp indicates an expected call of GetBlockByTimestamp.
func (mr *MockMetaStorageMockRecorder) GetBlockByTimestamp(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByTimestamp", reflect.TypeOf((*MockMetaStorage)(nil).GetBlockByTimestamp), arg0, arg1, arg2)
}

// GetBlockConsolidationCursor mocks base method.
func (m *MockMetaStorage) GetBlockConsolidationCursor(arg0 context.Context, arg1 string, arg2 uint32) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationCursor", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBlockConsolidationCursor indicates an expected call of GetBlockConsolidationCursor.
func (mr *MockMetaStorageMockRecorder) GetBlockConsolidationCursor(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationCursor", reflect.TypeOf((*MockMetaStorage)(nil).GetBlockConsolidationCursor), arg0, arg1, arg2)
}

// GetBlockConsolidationLegacy mocks base method.
func (m *MockMetaStorage) GetBlockConsolidationLegacy(arg0 context.Context, arg1 *chainstorage.BlockMetadata) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationLegacy", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockConsolidationLegacy indicates an expected call of GetBlockConsolidationLegacy.
func (mr *MockMetaStorageMockRecorder) GetBlockConsolidationLegacy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationLegacy", reflect.TypeOf((*MockMetaStorage)(nil).GetBlockConsolidationLegacy), arg0, arg1)
}

// GetBlockConsolidationShadow mocks base method.
func (m *MockMetaStorage) GetBlockConsolidationShadow(arg0 context.Context, arg1 *chainstorage.BlockMetadata) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationShadow", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockConsolidationShadow indicates an expected call of GetBlockConsolidationShadow.
func (mr *MockMetaStorageMockRecorder) GetBlockConsolidationShadow(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationShadow", reflect.TypeOf((*MockMetaStorage)(nil).GetBlockConsolidationShadow), arg0, arg1)
}

// GetBlockConsolidationShadowStats mocks base method.
func (m *MockMetaStorage) GetBlockConsolidationShadowStats(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) (*internal.ConsolidationShadowStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationShadowStats", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*internal.ConsolidationShadowStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockConsolidationShadowStats indicates an expected call of GetBlockConsolidationShadowStats.
func (mr *MockMetaStorageMockRecorder) GetBlockConsolidationShadowStats(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationShadowStats", reflect.TypeOf((*MockMetaStorage)(nil).GetBlockConsolidationShadowStats), arg0, arg1, arg2, arg3)
}

// GetBlocksByHeightRange mocks base method.
func (m *MockMetaStorage) GetBlocksByHeightRange(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksByHeightRange", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByHeightRange indicates an expected call of GetBlocksByHeightRange.
func (mr *MockMetaStorageMockRecorder) GetBlocksByHeightRange(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByHeightRange", reflect.TypeOf((*MockMetaStorage)(nil).GetBlocksByHeightRange), arg0, arg1, arg2, arg3)
}

// GetBlocksByHeights mocks base method.
func (m *MockMetaStorage) GetBlocksByHeights(arg0 context.Context, arg1 uint32, arg2 []uint64) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksByHeights", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByHeights indicates an expected call of GetBlocksByHeights.
func (mr *MockMetaStorageMockRecorder) GetBlocksByHeights(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByHeights", reflect.TypeOf((*MockMetaStorage)(nil).GetBlocksByHeights), arg0, arg1, arg2)
}

// GetBlocksConsolidationLegacy mocks base method.
func (m *MockMetaStorage) GetBlocksConsolidationLegacy(arg0 context.Context, arg1 []*chainstorage.BlockMetadata) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksConsolidationLegacy", arg0, arg1)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksConsolidationLegacy indicates an expected call of GetBlocksConsolidationLegacy.
func (mr *MockMetaStorageMockRecorder) GetBlocksConsolidationLegacy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksConsolidationLegacy", reflect.TypeOf((*MockMetaStorage)(nil).GetBlocksConsolidationLegacy), arg0, arg1)
}

// GetBlocksConsolidationShadow mocks base method.
func (m *MockMetaStorage) GetBlocksConsolidationShadow(arg0 context.Context, arg1 []*chainstorage.BlockMetadata) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksConsolidationShadow", arg0, arg1)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksConsolidationShadow indicates an expected call of GetBlocksConsolidationShadow.
func (mr *MockMetaStorageMockRecorder) GetBlocksConsolidationShadow(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksConsolidationShadow", reflect.TypeOf((*MockMetaStorage)(nil).GetBlocksConsolidationShadow), arg0, arg1)
}

// GetBlocksMissingConsolidationShadow mocks base method.
func (m *MockMetaStorage) GetBlocksMissingConsolidationShadow(arg0 context.Context, arg1 uint32, arg2, arg3, arg4 uint64) ([]*internal.BlockMetadataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksMissingConsolidationShadow", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*internal.BlockMetadataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksMissingConsolidationShadow indicates an expected call of GetBlocksMissingConsolidationShadow.
func (mr *MockMetaStorageMockRecorder) GetBlocksMissingConsolidationShadow(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksMissingConsolidationShadow", reflect.TypeOf((*MockMetaStorage)(nil).GetBlocksMissingConsolidationShadow), arg0, arg1, arg2, arg3, arg4)
}

// GetEventByEventId mocks base method.
func (m *MockMetaStorage) GetEventByEventId(arg0 context.Context, arg1 uint32, arg2 int64) (*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByEventId", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByEventId indicates an expected call of GetEventByEventId.
func (mr *MockMetaStorageMockRecorder) GetEventByEventId(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByEventId", reflect.TypeOf((*MockMetaStorage)(nil).GetEventByEventId), arg0, arg1, arg2)
}

// GetEventsAfterEventId mocks base method.
func (m *MockMetaStorage) GetEventsAfterEventId(arg0 context.Context, arg1 uint32, arg2 int64, arg3 uint64) ([]*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsAfterEventId", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsAfterEventId indicates an expected call of GetEventsAfterEventId.
func (mr *MockMetaStorageMockRecorder) GetEventsAfterEventId(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsAfterEventId", reflect.TypeOf((*MockMetaStorage)(nil).GetEventsAfterEventId), arg0, arg1, arg2, arg3)
}

// GetEventsByBlockHeight mocks base method.
func (m *MockMetaStorage) GetEventsByBlockHeight(arg0 context.Context, arg1 uint32, arg2 uint64) ([]*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByBlockHeight", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByBlockHeight indicates an expected call of GetEventsByBlockHeight.
func (mr *MockMetaStorageMockRecorder) GetEventsByBlockHeight(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByBlockHeight", reflect.TypeOf((*MockMetaStorage)(nil).GetEventsByBlockHeight), arg0, arg1, arg2)
}

// GetEventsByEventIdRange mocks base method.
func (m *MockMetaStorage) GetEventsByEventIdRange(arg0 context.Context, arg1 uint32, arg2, arg3 int64) ([]*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByEventIdRange", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByEventIdRange indicates an expected call of GetEventsByEventIdRange.
func (mr *MockMetaStorageMockRecorder) GetEventsByEventIdRange(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByEventIdRange", reflect.TypeOf((*MockMetaStorage)(nil).GetEventsByEventIdRange), arg0, arg1, arg2, arg3)
}

// GetFirstBlockMissingConsolidationShadow mocks base method.
func (m *MockMetaStorage) GetFirstBlockMissingConsolidationShadow(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstBlockMissingConsolidationShadow", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFirstBlockMissingConsolidationShadow indicates an expected call of GetFirstBlockMissingConsolidationShadow.
func (mr *MockMetaStorageMockRecorder) GetFirstBlockMissingConsolidationShadow(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstBlockMissingConsolidationShadow", reflect.TypeOf((*MockMetaStorage)(nil).GetFirstBlockMissingConsolidationShadow), arg0, arg1, arg2, arg3)
}

// GetFirstEventIdByBlockHeight mocks base method.
func (m *MockMetaStorage) GetFirstEventIdByBlockHeight(arg0 context.Context, arg1 uint32, arg2 uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstEventIdByBlockHeight", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstEventIdByBlockHeight indicates an expected call of GetFirstEventIdByBlockHeight.
func (mr *MockMetaStorageMockRecorder) GetFirstEventIdByBlockHeight(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstEventIdByBlockHeight", reflect.TypeOf((*MockMetaStorage)(nil).GetFirstEventIdByBlockHeight), arg0, arg1, arg2)
}

// GetFirstPromotableBlockConsolidationShadow mocks base method.
func (m *MockMetaStorage) GetFirstPromotableBlockConsolidationShadow(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPromotableBlockConsolidationShadow", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFirstPromotableBlockConsolidationShadow indicates an expected call of GetFirstPromotableBlockConsolidationShadow.
func (mr *MockMetaStorageMockRecorder) GetFirstPromotableBlockConsolidationShadow(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPromotableBlockConsolidationShadow", reflect.TypeOf((*MockMetaStorage)(nil).GetFirstPromotableBlockConsolidationShadow), arg0, arg1, arg2, arg3)
}

// GetLatestBlock mocks base method.
func (m *MockMetaStorage) GetLatestBlock(arg0 context.Context, arg1 uint32) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlock", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockMetaStorageMockRecorder) GetLatestBlock(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockMetaStorage)(nil).GetLatestBlock), arg0, arg1)
}

// GetMaxEventId mocks base method.
func (m *MockMetaStorage) GetMaxEventId(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxEventId", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxEventId indicates an expected call of GetMaxEventId.
func (mr *MockMetaStorageMockRecorder) GetMaxEventId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxEventId", reflect.TypeOf((*MockMetaStorage)(nil).GetMaxEventId), arg0, arg1)
}

// GetTransaction mocks base method.
func (m *MockMetaStorage) GetTransaction(arg0 context.Context, arg1 uint32, arg2 string) ([]*model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockMetaStorageMockRecorder) GetTransaction(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockMetaStorage)(nil).GetTransaction), arg0, arg1, arg2)
}

// PersistBlockConsolidationShadows mocks base method.
func (m *MockMetaStorage) PersistBlockConsolidationShadows(arg0 context.Context, arg1 []*internal.ConsolidationShadowPlacement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistBlockConsolidationShadows", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistBlockConsolidationShadows indicates an expected call of PersistBlockConsolidationShadows.
func (mr *MockMetaStorageMockRecorder) PersistBlockConsolidationShadows(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistBlockConsolidationShadows", reflect.TypeOf((*MockMetaStorage)(nil).PersistBlockConsolidationShadows), arg0, arg1)
}

// PersistBlockMetas mocks base method.
func (m *MockMetaStorage) PersistBlockMetas(arg0 context.Context, arg1 bool, arg2 []*chainstorage.BlockMetadata, arg3 *chainstorage.BlockMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistBlockMetas", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistBlockMetas indicates an expected call of PersistBlockMetas.
func (mr *MockMetaStorageMockRecorder) PersistBlockMetas(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistBlockMetas", reflect.TypeOf((*MockMetaStorage)(nil).PersistBlockMetas), arg0, arg1, arg2, arg3)
}

// PromoteBlockConsolidationShadows mocks base method.
func (m *MockMetaStorage) PromoteBlockConsolidationShadows(arg0 context.Context, arg1 uint32, arg2, arg3, arg4 uint64, arg5 time.Duration) (*internal.ConsolidationPromotionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteBlockConsolidationShadows", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*internal.ConsolidationPromotionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromoteBlockConsolidationShadows indicates an expected call of PromoteBlockConsolidationShadows.
func (mr *MockMetaStorageMockRecorder) PromoteBlockConsolidationShadows(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteBlockConsolidationShadows", reflect.TypeOf((*MockMetaStorage)(nil).PromoteBlockConsolidationShadows), arg0, arg1, arg2, arg3, arg4, arg5)
}

// SetBlockConsolidationCursor mocks base method.
func (m *MockMetaStorage) SetBlockConsolidationCursor(arg0 context.Context, arg1 string, arg2 uint32, arg3 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlockConsolidationCursor", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlockConsolidationCursor indicates an expected call of SetBlockConsolidationCursor.
func (mr *MockMetaStorageMockRecorder) SetBlockConsolidationCursor(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockConsolidationCursor", reflect.TypeOf((*MockMetaStorage)(nil).SetBlockConsolidationCursor), arg0, arg1, arg2, arg3)
}

// SetMaxEventId mocks base method.
func (m *MockMetaStorage) SetMaxEventId(arg0 context.Context, arg1 uint32, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaxEventId", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaxEventId indicates an expected call of SetMaxEventId.
func (mr *MockMetaStorageMockRecorder) SetMaxEventId(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxEventId", reflect.TypeOf((*MockMetaStorage)(nil).SetMaxEventId), arg0, arg1, arg2)
}

// MockEventStorage is a mock of EventStorage interface.
type MockEventStorage struct {
	ctrl     *gomock.Controller
	recorder *MockEventStorageMockRecorder
}

// MockEventStorageMockRecorder is the mock recorder for MockEventStorage.
type MockEventStorageMockRecorder struct {
	mock *MockEventStorage
}

// NewMockEventStorage creates a new mock instance.
func NewMockEventStorage(ctrl *gomock.Controller) *MockEventStorage {
	mock := &MockEventStorage{ctrl: ctrl}
	mock.recorder = &MockEventStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventStorage) EXPECT() *MockEventStorageMockRecorder {
	return m.recorder
}

// AddEventEntries mocks base method.
func (m *MockEventStorage) AddEventEntries(arg0 context.Context, arg1 uint32, arg2 []*model.EventEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEventEntries", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEventEntries indicates an expected call of AddEventEntries.
func (mr *MockEventStorageMockRecorder) AddEventEntries(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEventEntries", reflect.TypeOf((*MockEventStorage)(nil).AddEventEntries), arg0, arg1, arg2)
}

// AddEvents mocks base method.
func (m *MockEventStorage) AddEvents(arg0 context.Context, arg1 uint32, arg2 []*model.BlockEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEvents indicates an expected call of AddEvents.
func (mr *MockEventStorageMockRecorder) AddEvents(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvents", reflect.TypeOf((*MockEventStorage)(nil).AddEvents), arg0, arg1, arg2)
}

// GetEventByEventId mocks base method.
func (m *MockEventStorage) GetEventByEventId(arg0 context.Context, arg1 uint32, arg2 int64) (*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventByEventId", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventByEventId indicates an expected call of GetEventByEventId.
func (mr *MockEventStorageMockRecorder) GetEventByEventId(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventByEventId", reflect.TypeOf((*MockEventStorage)(nil).GetEventByEventId), arg0, arg1, arg2)
}

// GetEventsAfterEventId mocks base method.
func (m *MockEventStorage) GetEventsAfterEventId(arg0 context.Context, arg1 uint32, arg2 int64, arg3 uint64) ([]*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsAfterEventId", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsAfterEventId indicates an expected call of GetEventsAfterEventId.
func (mr *MockEventStorageMockRecorder) GetEventsAfterEventId(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsAfterEventId", reflect.TypeOf((*MockEventStorage)(nil).GetEventsAfterEventId), arg0, arg1, arg2, arg3)
}

// GetEventsByBlockHeight mocks base method.
func (m *MockEventStorage) GetEventsByBlockHeight(arg0 context.Context, arg1 uint32, arg2 uint64) ([]*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByBlockHeight", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByBlockHeight indicates an expected call of GetEventsByBlockHeight.
func (mr *MockEventStorageMockRecorder) GetEventsByBlockHeight(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByBlockHeight", reflect.TypeOf((*MockEventStorage)(nil).GetEventsByBlockHeight), arg0, arg1, arg2)
}

// GetEventsByEventIdRange mocks base method.
func (m *MockEventStorage) GetEventsByEventIdRange(arg0 context.Context, arg1 uint32, arg2, arg3 int64) ([]*model.EventEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByEventIdRange", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*model.EventEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByEventIdRange indicates an expected call of GetEventsByEventIdRange.
func (mr *MockEventStorageMockRecorder) GetEventsByEventIdRange(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByEventIdRange", reflect.TypeOf((*MockEventStorage)(nil).GetEventsByEventIdRange), arg0, arg1, arg2, arg3)
}

// GetFirstEventIdByBlockHeight mocks base method.
func (m *MockEventStorage) GetFirstEventIdByBlockHeight(arg0 context.Context, arg1 uint32, arg2 uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstEventIdByBlockHeight", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstEventIdByBlockHeight indicates an expected call of GetFirstEventIdByBlockHeight.
func (mr *MockEventStorageMockRecorder) GetFirstEventIdByBlockHeight(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstEventIdByBlockHeight", reflect.TypeOf((*MockEventStorage)(nil).GetFirstEventIdByBlockHeight), arg0, arg1, arg2)
}

// GetMaxEventId mocks base method.
func (m *MockEventStorage) GetMaxEventId(arg0 context.Context, arg1 uint32) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxEventId", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaxEventId indicates an expected call of GetMaxEventId.
func (mr *MockEventStorageMockRecorder) GetMaxEventId(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxEventId", reflect.TypeOf((*MockEventStorage)(nil).GetMaxEventId), arg0, arg1)
}

// SetMaxEventId mocks base method.
func (m *MockEventStorage) SetMaxEventId(arg0 context.Context, arg1 uint32, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaxEventId", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaxEventId indicates an expected call of SetMaxEventId.
func (mr *MockEventStorageMockRecorder) SetMaxEventId(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxEventId", reflect.TypeOf((*MockEventStorage)(nil).SetMaxEventId), arg0, arg1, arg2)
}

// MockBlockStorage is a mock of BlockStorage interface.
type MockBlockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockBlockStorageMockRecorder
}

// MockBlockStorageMockRecorder is the mock recorder for MockBlockStorage.
type MockBlockStorageMockRecorder struct {
	mock *MockBlockStorage
}

// NewMockBlockStorage creates a new mock instance.
func NewMockBlockStorage(ctrl *gomock.Controller) *MockBlockStorage {
	mock := &MockBlockStorage{ctrl: ctrl}
	mock.recorder = &MockBlockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockStorage) EXPECT() *MockBlockStorageMockRecorder {
	return m.recorder
}

// GetBlockByHash mocks base method.
func (m *MockBlockStorage) GetBlockByHash(arg0 context.Context, arg1 uint32, arg2 uint64, arg3 string) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHash", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHash indicates an expected call of GetBlockByHash.
func (mr *MockBlockStorageMockRecorder) GetBlockByHash(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHash", reflect.TypeOf((*MockBlockStorage)(nil).GetBlockByHash), arg0, arg1, arg2, arg3)
}

// GetBlockByHeight mocks base method.
func (m *MockBlockStorage) GetBlockByHeight(arg0 context.Context, arg1 uint32, arg2 uint64) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHeight", arg0, arg1, arg2)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHeight indicates an expected call of GetBlockByHeight.
func (mr *MockBlockStorageMockRecorder) GetBlockByHeight(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHeight", reflect.TypeOf((*MockBlockStorage)(nil).GetBlockByHeight), arg0, arg1, arg2)
}

// GetBlockByTimestamp mocks base method.
func (m *MockBlockStorage) GetBlockByTimestamp(arg0 context.Context, arg1 uint32, arg2 uint64) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByTimestamp", arg0, arg1, arg2)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByTimestamp indicates an expected call of GetBlockByTimestamp.
func (mr *MockBlockStorageMockRecorder) GetBlockByTimestamp(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByTimestamp", reflect.TypeOf((*MockBlockStorage)(nil).GetBlockByTimestamp), arg0, arg1, arg2)
}

// GetBlockConsolidationCursor mocks base method.
func (m *MockBlockStorage) GetBlockConsolidationCursor(arg0 context.Context, arg1 string, arg2 uint32) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationCursor", arg0, arg1, arg2)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBlockConsolidationCursor indicates an expected call of GetBlockConsolidationCursor.
func (mr *MockBlockStorageMockRecorder) GetBlockConsolidationCursor(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationCursor", reflect.TypeOf((*MockBlockStorage)(nil).GetBlockConsolidationCursor), arg0, arg1, arg2)
}

// GetBlockConsolidationLegacy mocks base method.
func (m *MockBlockStorage) GetBlockConsolidationLegacy(arg0 context.Context, arg1 *chainstorage.BlockMetadata) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationLegacy", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockConsolidationLegacy indicates an expected call of GetBlockConsolidationLegacy.
func (mr *MockBlockStorageMockRecorder) GetBlockConsolidationLegacy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationLegacy", reflect.TypeOf((*MockBlockStorage)(nil).GetBlockConsolidationLegacy), arg0, arg1)
}

// GetBlockConsolidationShadow mocks base method.
func (m *MockBlockStorage) GetBlockConsolidationShadow(arg0 context.Context, arg1 *chainstorage.BlockMetadata) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationShadow", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockConsolidationShadow indicates an expected call of GetBlockConsolidationShadow.
func (mr *MockBlockStorageMockRecorder) GetBlockConsolidationShadow(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationShadow", reflect.TypeOf((*MockBlockStorage)(nil).GetBlockConsolidationShadow), arg0, arg1)
}

// GetBlockConsolidationShadowStats mocks base method.
func (m *MockBlockStorage) GetBlockConsolidationShadowStats(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) (*internal.ConsolidationShadowStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockConsolidationShadowStats", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*internal.ConsolidationShadowStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockConsolidationShadowStats indicates an expected call of GetBlockConsolidationShadowStats.
func (mr *MockBlockStorageMockRecorder) GetBlockConsolidationShadowStats(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockConsolidationShadowStats", reflect.TypeOf((*MockBlockStorage)(nil).GetBlockConsolidationShadowStats), arg0, arg1, arg2, arg3)
}

// GetBlocksByHeightRange mocks base method.
func (m *MockBlockStorage) GetBlocksByHeightRange(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksByHeightRange", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByHeightRange indicates an expected call of GetBlocksByHeightRange.
func (mr *MockBlockStorageMockRecorder) GetBlocksByHeightRange(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByHeightRange", reflect.TypeOf((*MockBlockStorage)(nil).GetBlocksByHeightRange), arg0, arg1, arg2, arg3)
}

// GetBlocksByHeights mocks base method.
func (m *MockBlockStorage) GetBlocksByHeights(arg0 context.Context, arg1 uint32, arg2 []uint64) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksByHeights", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByHeights indicates an expected call of GetBlocksByHeights.
func (mr *MockBlockStorageMockRecorder) GetBlocksByHeights(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByHeights", reflect.TypeOf((*MockBlockStorage)(nil).GetBlocksByHeights), arg0, arg1, arg2)
}

// GetBlocksConsolidationLegacy mocks base method.
func (m *MockBlockStorage) GetBlocksConsolidationLegacy(arg0 context.Context, arg1 []*chainstorage.BlockMetadata) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksConsolidationLegacy", arg0, arg1)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksConsolidationLegacy indicates an expected call of GetBlocksConsolidationLegacy.
func (mr *MockBlockStorageMockRecorder) GetBlocksConsolidationLegacy(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksConsolidationLegacy", reflect.TypeOf((*MockBlockStorage)(nil).GetBlocksConsolidationLegacy), arg0, arg1)
}

// GetBlocksConsolidationShadow mocks base method.
func (m *MockBlockStorage) GetBlocksConsolidationShadow(arg0 context.Context, arg1 []*chainstorage.BlockMetadata) ([]*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksConsolidationShadow", arg0, arg1)
	ret0, _ := ret[0].([]*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksConsolidationShadow indicates an expected call of GetBlocksConsolidationShadow.
func (mr *MockBlockStorageMockRecorder) GetBlocksConsolidationShadow(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksConsolidationShadow", reflect.TypeOf((*MockBlockStorage)(nil).GetBlocksConsolidationShadow), arg0, arg1)
}

// GetBlocksMissingConsolidationShadow mocks base method.
func (m *MockBlockStorage) GetBlocksMissingConsolidationShadow(arg0 context.Context, arg1 uint32, arg2, arg3, arg4 uint64) ([]*internal.BlockMetadataRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksMissingConsolidationShadow", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*internal.BlockMetadataRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksMissingConsolidationShadow indicates an expected call of GetBlocksMissingConsolidationShadow.
func (mr *MockBlockStorageMockRecorder) GetBlocksMissingConsolidationShadow(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksMissingConsolidationShadow", reflect.TypeOf((*MockBlockStorage)(nil).GetBlocksMissingConsolidationShadow), arg0, arg1, arg2, arg3, arg4)
}

// GetFirstBlockMissingConsolidationShadow mocks base method.
func (m *MockBlockStorage) GetFirstBlockMissingConsolidationShadow(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstBlockMissingConsolidationShadow", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFirstBlockMissingConsolidationShadow indicates an expected call of GetFirstBlockMissingConsolidationShadow.
func (mr *MockBlockStorageMockRecorder) GetFirstBlockMissingConsolidationShadow(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstBlockMissingConsolidationShadow", reflect.TypeOf((*MockBlockStorage)(nil).GetFirstBlockMissingConsolidationShadow), arg0, arg1, arg2, arg3)
}

// GetFirstPromotableBlockConsolidationShadow mocks base method.
func (m *MockBlockStorage) GetFirstPromotableBlockConsolidationShadow(arg0 context.Context, arg1 uint32, arg2, arg3 uint64) (uint64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstPromotableBlockConsolidationShadow", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetFirstPromotableBlockConsolidationShadow indicates an expected call of GetFirstPromotableBlockConsolidationShadow.
func (mr *MockBlockStorageMockRecorder) GetFirstPromotableBlockConsolidationShadow(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstPromotableBlockConsolidationShadow", reflect.TypeOf((*MockBlockStorage)(nil).GetFirstPromotableBlockConsolidationShadow), arg0, arg1, arg2, arg3)
}

// GetLatestBlock mocks base method.
func (m *MockBlockStorage) GetLatestBlock(arg0 context.Context, arg1 uint32) (*chainstorage.BlockMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlock", arg0, arg1)
	ret0, _ := ret[0].(*chainstorage.BlockMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockBlockStorageMockRecorder) GetLatestBlock(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockBlockStorage)(nil).GetLatestBlock), arg0, arg1)
}

// PersistBlockConsolidationShadows mocks base method.
func (m *MockBlockStorage) PersistBlockConsolidationShadows(arg0 context.Context, arg1 []*internal.ConsolidationShadowPlacement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistBlockConsolidationShadows", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistBlockConsolidationShadows indicates an expected call of PersistBlockConsolidationShadows.
func (mr *MockBlockStorageMockRecorder) PersistBlockConsolidationShadows(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistBlockConsolidationShadows", reflect.TypeOf((*MockBlockStorage)(nil).PersistBlockConsolidationShadows), arg0, arg1)
}

// PersistBlockMetas mocks base method.
func (m *MockBlockStorage) PersistBlockMetas(arg0 context.Context, arg1 bool, arg2 []*chainstorage.BlockMetadata, arg3 *chainstorage.BlockMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistBlockMetas", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistBlockMetas indicates an expected call of PersistBlockMetas.
func (mr *MockBlockStorageMockRecorder) PersistBlockMetas(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistBlockMetas", reflect.TypeOf((*MockBlockStorage)(nil).PersistBlockMetas), arg0, arg1, arg2, arg3)
}

// PromoteBlockConsolidationShadows mocks base method.
func (m *MockBlockStorage) PromoteBlockConsolidationShadows(arg0 context.Context, arg1 uint32, arg2, arg3, arg4 uint64, arg5 time.Duration) (*internal.ConsolidationPromotionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteBlockConsolidationShadows", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*internal.ConsolidationPromotionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromoteBlockConsolidationShadows indicates an expected call of PromoteBlockConsolidationShadows.
func (mr *MockBlockStorageMockRecorder) PromoteBlockConsolidationShadows(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteBlockConsolidationShadows", reflect.TypeOf((*MockBlockStorage)(nil).PromoteBlockConsolidationShadows), arg0, arg1, arg2, arg3, arg4, arg5)
}

// SetBlockConsolidationCursor mocks base method.
func (m *MockBlockStorage) SetBlockConsolidationCursor(arg0 context.Context, arg1 string, arg2 uint32, arg3 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBlockConsolidationCursor", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBlockConsolidationCursor indicates an expected call of SetBlockConsolidationCursor.
func (mr *MockBlockStorageMockRecorder) SetBlockConsolidationCursor(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBlockConsolidationCursor", reflect.TypeOf((*MockBlockStorage)(nil).SetBlockConsolidationCursor), arg0, arg1, arg2, arg3)
}

// MockTransactionStorage is a mock of TransactionStorage interface.
type MockTransactionStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionStorageMockRecorder
}

// MockTransactionStorageMockRecorder is the mock recorder for MockTransactionStorage.
type MockTransactionStorageMockRecorder struct {
	mock *MockTransactionStorage
}

// NewMockTransactionStorage creates a new mock instance.
func NewMockTransactionStorage(ctrl *gomock.Controller) *MockTransactionStorage {
	mock := &MockTransactionStorage{ctrl: ctrl}
	mock.recorder = &MockTransactionStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionStorage) EXPECT() *MockTransactionStorageMockRecorder {
	return m.recorder
}

// AddTransactions mocks base method.
func (m *MockTransactionStorage) AddTransactions(arg0 context.Context, arg1 []*model.Transaction, arg2 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTransactions", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTransactions indicates an expected call of AddTransactions.
func (mr *MockTransactionStorageMockRecorder) AddTransactions(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTransactions", reflect.TypeOf((*MockTransactionStorage)(nil).AddTransactions), arg0, arg1, arg2)
}

// GetTransaction mocks base method.
func (m *MockTransactionStorage) GetTransaction(arg0 context.Context, arg1 uint32, arg2 string) ([]*model.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockTransactionStorageMockRecorder) GetTransaction(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockTransactionStorage)(nil).GetTransaction), arg0, arg1, arg2)
}
