api:
  streaming_max_no_event_time: 15m
chain:
  block_tag:
    latest: 2
    stable: 2
  block_time: 2s
  event_tag:
    latest: 2
    stable: 2
  client:
    retry:
      max_attempts: 5
  irreversible_distance: 400
  feature:
    rosetta_parser: true
    default_stable_event: true
    block_validation_enabled: true
    block_validation_muted: true
aws:
  aws_account: development
  dynamodb:
    event_table: example_chainstorage_block_events_{{blockchain}}_{{network}}
    event_table_height_index: example_chainstorage_block_events_by_height_{{blockchain}}_{{network}}
sla:
  block_height_delta: 100 # reorg distance is high according to https://polygonscan.com/blocks_forked
  block_time_delta: 4m
  out_of_sync_node_distance: 400
  tier: 1
  time_since_last_block: 5m
  event_height_delta: 100
  event_time_delta: 4m
  time_since_last_event: 5m
  expected_workflows:
    - monitor
    - poller
    - streamer
    - cross_validator
workflows:
  backfiller:
    batch_size: 2500
    checkpoint_size: 5000
    num_concurrent_extractors: 120
    max_reprocessed_per_batch: 100
    failover_enabled: true
  benchmarker:
    child_workflow_execution_start_to_close_timeout: 2h
  cross_validator:
    backoff_interval: 0s
    checkpoint_size: 500
    validation_start_height: 44000000
    validation_percentage: 100
  monitor:
    backoff_interval: 2s
    failover_enabled: true
  poller:
    backoff_interval: 0s
    checkpoint_size: 250
    max_blocks_to_sync_per_cycle: 300
    parallelism: 24
    failover_enabled: true
    consensus_failover_enabled: true
    consensus_validation: true
    consensus_validation_muted: true
    session_enabled: true
  streamer:
    backoff_interval: 0s
