aws:
  aws_account: development
cron:
  disable_node_canary: false
  disable_polling_canary: false
  disable_streaming_canary: false
sla:
  block_height_delta: 40
  block_time_delta: 2m
  out_of_sync_node_distance: 40
  time_since_last_block: 3m
  event_height_delta: 40
  event_time_delta: 2m
  tier: 2
  time_since_last_event: 3m
workflows:
  backfiller:
    num_concurrent_extractors: 16
  poller:
    backoff_interval: 1s
    parallelism: 20
  monitor:
    backoff_interval: 3s
  streamer:
    backoff_interval: 1s
chain:
  block_tag:
    latest: 2
    stable: 2
  block_time: 3s
  event_tag:
    latest: 1
    stable: 1
  irreversible_distance: 20
