chain:
  block_time: 2s
  event_tag:
    latest: 1
    stable: 1
  irreversible_distance: 1
sla:
  block_height_delta: 20
  block_time_delta: 40s
  out_of_sync_node_distance: 30
  tier: 2
  time_since_last_block: 1m
  event_height_delta: 20
  event_time_delta: 40s
  time_since_last_event: 1m
  expected_workflows:
    - monitor
    - poller
    - streamer
    - cross_validator
workflows:
  poller:
    backoff_interval: 1s
    max_blocks_to_sync_per_cycle: 300
    parallelism: 24
    fast_sync: true
  streamer:
    backoff_interval: 1s
  backfiller:
    num_concurrent_extractors: 100
  cross_validator:
    batch_size: 1000
    validation_percentage: 1
  migrator:
    activity_retry:
      backoff_coefficient: 2
      initial_interval: 10s
      maximum_attempts: 3
      maximum_interval: 3m
    activity_schedule_to_close_timeout: 1h
    activity_start_to_close_timeout: 30m
    backoff_interval: 5s
    batch_size: 1000
    checkpoint_size: 5000
    task_list: default
    workflow_identity: workflow.migrator
    workflow_run_timeout: 24h
